name: "📑 Documentation Update"
description: "Improve Documentation"
title: "DOC:"
labels: [documentation]
body:
  - type: textarea
    attributes:
      label: "What's wrong with the existing documentation"
      description: "Which things do we need to add or delete"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Add ScreenShots"
      description: "Add sufficient SS to explain your issue."
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I'm a GSSOC'24 contributor"
        - label: "I'm a VSoC'24 contributor"
        - label: "I want to work on this issue"
